--------------------------------------------------------
-- Archivo creado  - viernes-octubre-02-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPETITIONS
--------------------------------------------------------

  CREATE TABLE "ESBCOL"."COMPETITIONS" 
   (	"COMPETITIONS_ID" NUMBER(10,0), 
	"EVALUATE_FACTOR1" NUMBER, 
	"EVALUATE_FACTOR2" NUMBER, 
	"EVALUATE_FACTOR3" NUMBER, 
	"EVALUATE_FACTOR4" NUMBER, 
	"EVALUATE_FACTOR5" NUMBER, 
	"EVALUATE_FACTOR6" NUMBER, 
	"EVALUATE_FACTOR7" NUMBER, 
	"EVALUATE_FACTOR8" NUMBER, 
	"EVALUATE_FACTOR9" NUMBER, 
	"EVALUATE_FACTOR10" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ESBCOL.COMPETITIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007085
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESBCOL"."SYS_C007085" ON "ESBCOL"."COMPETITIONS" ("COMPETITIONS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMPETITIONS
--------------------------------------------------------

  ALTER TABLE "ESBCOL"."COMPETITIONS" ADD PRIMARY KEY ("COMPETITIONS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESBCOL"."COMPETITIONS" MODIFY ("COMPETITIONS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger COMPETITIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ESBCOL"."COMPETITIONS_TRG" 
BEFORE INSERT ON COMPETITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COMPETITIONS_ID IS NULL THEN
      SELECT COMPETITIONS_SEQ.NEXTVAL INTO :NEW.COMPETITIONS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ESBCOL"."COMPETITIONS_TRG" ENABLE;
